apps/tracker/urls.py
from django.urls import path
from .views import views, views_parital, views_api

app_name = "tracker"

urlpatterns = [
    path("", views.dashboard_view, name="dashboard"),
    # Page views
    path("create-wanted/", views.create_wanted_view, name="create_wanted"),
    path("wanted/", views.wanted_view, name="wanted"),
    # API views
    path(
        "api/buy-all/<wanted_id>/", views_api.buy_all_cards_view, name="buy_all_cards"
    ),
    # Partial views (htmx)
    path(
        "wanted/<int:wanted_id>/",
        views_parital.wanted_detail_view,
        name="wanted_detail",
    ),
    path(
        "add-value/<int:resource_id>/", views_parital.add_value_view, name="add_value"
    ),
]

dofRessTrack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tracker/", include("apps.tracker.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tracker/models.py
from enum import Enum
from django.db import models
from django.utils import timezone
from datetime import timedelta


class ResourceType(Enum):
    ITEM = 0
    CRAFT = 1
    HARVEST = 2
    BOSS = 3
    MONSTER = 4
    WANTED = 5
    CARD = 6
    QUEST = 7


class Resource(models.Model):
    name = models.CharField(max_length=255)
    image = models.ForeignKey(
        "ResourceImage", on_delete=models.SET_NULL, null=True, blank=True
    )
    resource_type = models.IntegerField(
        choices=[(tag.value, tag.name) for tag in ResourceType]
    )
    use_in = models.ManyToManyField(
        "self", symmetrical=False, related_name="used_for", blank=True
    )

    def __str__(self):
        return self.name

    def add_stats(self):
        self.current_value = ResourceValue.get_last_value(self)
        self.average_value = ResourceValue.get_average_price(self, days=30)


class ResourceImage(models.Model):
    name = models.CharField(max_length=255, unique=True, null=True, blank=True)
    image = models.ImageField(upload_to="resources/images/")

    def __str__(self):
        return self.name if self.name else f"Image {self.id}"


class ResourceValue(models.Model):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    value = models.SmallIntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.resource.name} at {self.timestamp}"

    @staticmethod
    def get_average_price(resource: Resource, days=7):
        time_threshold = timezone.now() - timedelta(days=days)
        values = ResourceValue.objects.filter(
            resource_id=resource.id, timestamp__gte=time_threshold
        )
        if values.exists():
            return values.aggregate(models.Avg("value"))["value__avg"]
        return None

    @staticmethod
    def get_last_value(resource: Resource):
        return (
            ResourceValue.objects.filter(resource=resource)
            .order_by("-timestamp")
            .values_list("value", flat=True)
            .first()
        )


class BuyIn(models.Model):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    price = models.SmallIntegerField()
    quantity = models.SmallIntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"BuyIn of {self.quantity} {self.resource.name} at {self.price} on {self.timestamp}"

    @staticmethod
    def get_average_buy_in_price(resource: Resource, days=7):
        time_threshold = timezone.now() - timedelta(days=days)
        buys = BuyIn.objects.filter(
            resource_id=resource.id, timestamp__gte=time_threshold
        )
        if buys.exists():
            return buys.aggregate(models.Avg("price"))["price__avg"]
        return None

    @staticmethod
    def get_last_buy_in_price(resource: Resource):
        return (
            BuyIn.objects.filter(resource=resource)
            .order_by("-timestamp")
            .values_list("price", flat=True)
            .first()
        )


class SellOut(models.Model):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    price = models.SmallIntegerField()
    quantity = models.SmallIntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"SellOut of {self.quantity} {self.resource.name} at {self.price} on {self.timestamp}"

    @staticmethod
    def get_average_sell_out_price(resource: Resource, days=7):
        time_threshold = timezone.now() - timedelta(days=days)
        sells = SellOut.objects.filter(
            resource_id=resource.id, timestamp__gte=time_threshold
        )
        if sells.exists():
            return sells.aggregate(models.Avg("price"))["price__avg"]
        return None

    @staticmethod
    def get_last_sell_out_price(resource: Resource):
        return (
            SellOut.objects.filter(resource=resource)
            .order_by("-timestamp")
            .values_list("price", flat=True)
            .first()
        )

apps/tracker/forms.py
from django import forms
from .models import ResourceValue


class ResourceValueForm(forms.ModelForm):
    class Meta:
        model = ResourceValue
        fields = ["value"]

apps/tracker/views.py
from django.shortcuts import redirect, render


from .models import Resource, ResourceImage, ResourceType


def dashboard_view(request):
    return render(request, "tracker/dashboard.html")


def wanted_view(request):
    wanteds = Resource.objects.filter(resource_type=ResourceType.WANTED.value)
    return render(request, "tracker/wanted.html", {"wanteds": wanteds})


def create_wanted_view(request):
    if request.method == "GET":
        return render(request, "tracker/createWanted.html")

    name = request.POST.get("name")
    wanted_name = request.POST.get("wanted_name")
    nb = request.POST.get("nb")
    image = request.FILES.get("image")

    card_img = ResourceImage.objects.get(name="Carte")
    frag_img = ResourceImage.objects.get(name="Fragment carte")

    ress_img, created = ResourceImage.objects.get_or_create(name=name)
    if created:
        ress_img.image.save(image.name, image)

    ress = Resource.objects.create(
        name=name, image=ress_img, resource_type=ResourceType.WANTED.value
    )
    card = Resource.objects.create(
        name=f"Carte de {wanted_name}",
        image=card_img,
        resource_type=ResourceType.CARD.value,
    )
    card.use_in.add(ress)

    for i in range(int(nb)):
        Resource.objects.create(
            name=f"Fragment de carte {wanted_name} {i + 1}/{nb}",
            image=frag_img,
            resource_type=ResourceType.CARD.value,
        ).use_in.add(card)

    return redirect("tracker:create_wanted")

apps/tracker/views/views.py
from django.shortcuts import redirect, render


from apps.tracker.models import Resource, ResourceImage, ResourceType


def dashboard_view(request):
    return render(request, "tracker/dashboard.html")


def wanted_view(request):
    wanteds = Resource.objects.filter(resource_type=ResourceType.WANTED.value)
    return render(request, "tracker/wanted.html", {"wanteds": wanteds})


def create_wanted_view(request):
    if request.method == "GET":
        return render(request, "tracker/createWanted.html")

    name = request.POST.get("name")
    wanted_name = request.POST.get("wanted_name")
    nb = request.POST.get("nb")
    image = request.FILES.get("image")

    card_img = ResourceImage.objects.get(name="Carte")
    frag_img = ResourceImage.objects.get(name="Fragment carte")

    ress_img, created = ResourceImage.objects.get_or_create(name=name)
    if created:
        ress_img.image.save(image.name, image)

    ress = Resource.objects.create(
        name=name, image=ress_img, resource_type=ResourceType.WANTED.value
    )
    card = Resource.objects.create(
        name=f"Carte de {wanted_name}",
        image=card_img,
        resource_type=ResourceType.CARD.value,
    )
    card.use_in.add(ress)

    for i in range(int(nb)):
        Resource.objects.create(
            name=f"Fragment de carte {wanted_name} {i + 1}/{nb}",
            image=frag_img,
            resource_type=ResourceType.CARD.value,
        ).use_in.add(card)

    return redirect("tracker:create_wanted")

apps/tracker/views/views_api.py
from django.http.response import HttpResponse
from django.db.models.expressions import Subquery
from django.db.models.expressions import OuterRef
from django.views.decorators.http import require_http_methods

from apps.tracker.models import BuyIn, Resource, ResourceType, ResourceValue


@require_http_methods(["POST"])
def buy_all_cards_view(request, wanted_id):
    latest_value = (
        ResourceValue.objects.filter(resource=OuterRef("pk"))
        .order_by("-timestamp")
        .values("value")[:1]
    )

    fragments = Resource.objects.filter(
        use_in__use_in__id=wanted_id,
        resource_type=ResourceType.CARD.value,
    ).annotate(latest_value=Subquery(latest_value))

    if not fragments:
        return HttpResponse("No fragments found for the wanted item", status=404)

    BuyIn.objects.bulk_create(
        [
            BuyIn(
                resource=fragment,
                price=fragment.latest_value if fragment.latest_value else 0,
                quantity=1,
            )
            for fragment in fragments
        ]
    )

    return HttpResponse("Buy all cards executed", status=200)

apps/tracker/views/views_parital.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods

from apps.tracker.models import ResourceValue, SellOut, Resource, ResourceType

from apps.tracker.forms import ResourceValueForm


@require_http_methods(["POST"])
def wanted_detail_view(request, wanted_id):
    wanted = get_object_or_404(Resource, id=wanted_id)
    if wanted.resource_type != ResourceType.WANTED.value:
        raise Http404("Wanted not found")

    wanted.add_stats()
    wanted.last_sell_value = SellOut.get_last_sell_out_price(wanted)
    wanted.average_sell_values = SellOut.get_average_sell_out_price(wanted, days=30)

    card = Resource.objects.filter(
        use_in=wanted, resource_type=ResourceType.CARD.value
    ).first()

    fragments = Resource.objects.filter(
        use_in=card, resource_type=ResourceType.CARD.value
    ).order_by("name")

    cards = list(fragments) + [card]

    for card in cards:
        card.add_stats()

    wanted.all_card_price = sum(
        [card.current_value for card in cards[:-1] if card.current_value]
    )

    form = ResourceValueForm()
    context = {
        "form": form,
        "wanted": wanted,
        "cards": cards,
    }

    response = render(
        request,
        "tracker/partials/wanted-detail.html",
        context,
    )
    response["HX-Trigger"] = "wantedDetailLoaded"
    return response


@require_http_methods(["POST"])
def add_value_view(request, resource_id):
    resource = get_object_or_404(Resource, id=resource_id)

    form = ResourceValueForm(request.POST)
    if not form.is_valid():
        raise NotImplementedError("Form validation not implemented yet")

    value = form.cleaned_data["value"]
    ResourceValue.objects.create(resource=resource, value=value)

    resource.add_stats()

    response = render(
        request, "tracker/partials/resource-price.html", {"resource": resource}
    )
    response["HX-Trigger"] = "resourceValueAdded"
    return response

apps/tracker/templates/tracker/createWanted.html
{% extends 'layout.html' %}
{% block title %}Create Wanted{% endblock %}
{% block content %}
    <h1>Create a New Waned Entry</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required />
        <br>
        <label for="wanted_name">Wanted Name:</label>
        <input type="text" id="wanted_name" name="wanted_name" required />
        <br>
        <label for="nb">NB:</label>
        <input type="text" id="nb" name="nb" required />
        <br>
        <label for="image">Image:</label>
        <input type="file" id="image" name="image" accept="image/*" required />
        <br>
        <input type="submit" value="Create Wanted Entry" />
    </form>
{% endblock %}

apps/tracker/templates/tracker/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block extra_css %}
    <link href="{% static 'tracker/css/dashboard.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <h1>Dashboard</h1>
    <ul>
        <li>
            <a href="{% url 'tracker:wanted' %}">View Wanted Entry</a>
        </li>
        <li>
            <a href="{% url 'tracker:create_wanted' %}">Create Wanted Entry</a>
        </li>
    </ul>
{% endblock %}

apps/tracker/templates/tracker/wanted.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}Wanted{% endblock %}
{% block extra_css %}
    <link href="{% static 'tracker/css/wanted-detail.css' %}" rel="stylesheet" />
    <link href="{% static 'tracker/css/wanted-list.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'tracker/css/modal.css' %}" />
{% endblock %}
{% block extra_js %}
    <script src="{% static 'tracker/js/value-modal.js' %}" defer></script>
    <script src="{% static 'tracker/js/wanted-detail.js' %}" defer></script>
{% endblock %}
{% block content %}
    {% include 'tracker/partials/wanted-list.html' %}
    {% include 'tracker/partials/wanted-detail.html' %}
{% endblock %}

apps/tracker/templates/tracker/wanted_detail.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}{{ wanted.name }}{% endblock %}
{% block extra_css %}
    <link href="{% static 'tracker/css/wanted-detail.css' %}" rel="stylesheet" />
    <link href="{% static 'tracker/css/wanted-list.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    {% include 'tracker/partials/wanted-list.html' %}
    <div class="back-link">
        <a href="{% url 'tracker:wanted' %}">Back to Wanted List</a>
    </div>
    <div class="wanted-detail-container">
        <h1>{{ wanted.name }}</h1>
        <div class="wanted-info">
            <div class="wanted-section open-value-modal"
                 data-name="{{ wanted.name }}"
                 data-id="{{ wanted.id }}">
                <div class="wanted-image">
                    <img src="{{ wanted.image.image.url }}" alt="{{ wanted.wanted_name }}" />
                </div>
                <div class="wanted-price" id="resource-price-{{ wanted.id }}">
                    {% include 'tracker/partials/resource-price.html'  with resource=wanted %}
                </div>
                <div class="wanted-sell">
                    <h2>Last Sell : {{ wanted.last_sell_value }} K</h2>
                    <h3>Average Sell : {{ wanted.average_sell_values }} K</h3>
                </div>
            </div>
            <div class="cards-section">
                {% for card in cards %}
                    <div class="card open-value-modal"
                         data-name="{{ card.name }}"
                         data-id="{{ card.id }}">
                        <div class="card-image">
                            <img src="{{ card.image.image.url }}" alt="Fragment {{ forloop.counter }}" />
                        </div>
                        <div class="card-info">
                            <h3>{{ card.name }}</h3>
                        </div>
                        <div class="card-price" id="resource-price-{{ card.id }}">
                            {% include 'tracker/partials/resource-price.html' with resource=card %}
                        </div>
                    </div>
                {% empty %}
                    <p>No card available.</p>
                {% endfor %}
            </div>
        </div>
    </div>
    {% include 'tracker/partials/value_modal.html' %}
{% endblock %}